name: simplest_logger
description: "A lightweight, opinionated, colorful logging utility for Dart applications. Minimal configuration necessary."
version: 1.0.6
repository: "https://github.com/sunderee/simplest-logger"

topics:
  - logging
  - logger

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0